source 'https://rubygems.org'

gem 'sinatra', :require => false
gem 'haml'
gem 'rerun'
gem 'em-websocket'
gem 'em-hiredis'
gem "redis"
gem 'eventmachine', :git => 'git://github.com/eventmachine/eventmachine.git'
