source 'https://rubygems.org'

gem 'sinatra', :require => false
gem 'haml'
gem 'rerun'
gem 'em-websocket'
gem 'em-hiredis'
gem 'eventmachine', :git => 'git://github.com/eventmachine/eventmachine.git'
gem 'thin'
gem "redis", "~> 3.0.6"
gem "sinatra-flash", "~> 0.3.0"
gem "video_info", "~> 2.0.2"

